### ISSUE TITLE
Tracking issue for CI breakages caused by Ubuntu 22.04 migration

### ISSUE THREAD

**Issue by embg** [facebook/zstd#3329]
Github Actions recently migrated to [Ubuntu 22.04](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/), which has broken some of our CI jobs due to new compiler versions etc. I opened a [test PR](https://github.com/embg/zstd/pull/37) in my zstd fork to identify breakages:

- [x] #3330 @embg is taking this one.
- [x] The stack size check in the linux-kernel check is broken. [Failing job](https://github.com/embg/zstd/actions/runs/3596636191/jobs/6057530648). @terrelln is going to look at this.
- [x] Our QEMU M68K test is broken. [Failing job](https://github.com/embg/zstd/actions/runs/3596636191/jobs/6057533781). It looks like a bug in QEMU that's been exposed by a new compiler version. ~~This one is up for grabs.~~ @Cyan4973 is taking this one.

**Comment by Cyan4973** [comment]
I can look into the `m68k` issue

**Comment by Cyan4973** [comment]
All issues fixed now
