### ISSUE TITLE
API evolution plan

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#3390]
* v1.5.4
  * [x] Deprecate `ZSTD_copyCCtx()` & `ZSTD_copyDCtx()` (PR #3196)
  * [x] Deprecate advanced streaming functions (https://github.com/facebook/zstd/issues/3405)
* v1.5.6
  * [x] Move `ZSTD_c_targetCBlockSize` CCtx parameter to stable (PR #3964)
* v1.6.0
  * [ ] Move `ZSTD_frameHeader` and `ZSTD_getFrameHeader()` to stable (Issue #2471)
  * [ ] Delete `ZSTD_copyCCtx()` & `ZSTD_copyDCtx()`
  * [ ] Disable Legacy Decoders `v0.5` `v0.6` and `v0.7` by default (can still be enabled on-demand)
  * [ ] Move `ZSTD_createDDict_byReference()` to stable https://github.com/facebook/zstd/issues/4283
  * [ ] Move `ZSTD_DCtx_loadDictionary_advanced()` to stable https://github.com/facebook/zstd/issues/3723
  * [ ] Remove deprecated `ZBUFF_` API

**Comment by terrelln** [comment]
Adding this issue to track our plans for API evolution. Mainly moving functions to stable, or deprecating & deleting old functions. Marked as `release-blocking` so we don't forget about it in releases.

**Comment by ghost** [comment]
#3213, this could be a candidate.

**Comment by embg** [comment]
There are a few additional deprecations for 1.5.4: https://github.com/facebook/zstd/issues/3405
